package gateway

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"sync"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
)

// mountAdmin registers the dashboard admin endpoints on the given router. These
// manage API keys, provider accounts, routing chains, budgets, and usage.

// adminCodexResetCredits fetches available Codex rate-limit reset credits and
// their expiry details from the ChatGPT backend API. Only valid for Codex
// (OpenAI) accounts with OAuth credentials.
func (s *Server) adminCodexResetCredits(w http.ResponseWriter, r *http.Request) {
	acc, err := s.accounts.Get(r.Context(), chi.URLParam(r, "id"))
	if err != nil {
		writeError(w, http.StatusNotFound, "account not found")
		return
	}
	if acc.Provider != "codex" {
		writeError(w, http.StatusBadRequest, "only supported for codex accounts")
		return
	}
	if s.vault == nil {
		writeError(w, http.StatusInternalServerError, "vault not configured")
		return
	}

	creds, err := s.vault.Open(acc)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "could not decrypt credentials")
		return
	}
	if creds.AccessToken == "" {
		writeError(w, http.StatusBadRequest, "no access token available; re-authorize the connection")
		return
	}

	ctx, cancel := context.WithTimeout(r.Context(), 15*time.Second)
	defer cancel()

	result, ferr := fetchCodexResetCredits(ctx, creds.AccessToken, creds.Extra)
	if ferr != nil {
		writeError(w, http.StatusBadGateway, sanitizeProviderError(s.log, ferr, "Codex reset credits request failed"))
		return
	}
	writeJSON(w, http.StatusOK, result)
}

// adminCodexConsumeCredit consumes one Codex rate-limit reset credit. This is
// irreversible — it permanently spends 1 credit to reset the user's rate limit.
func (s *Server) adminCodexConsumeCredit(w http.ResponseWriter, r *http.Request) {
	acc, err := s.accounts.Get(r.Context(), chi.URLParam(r, "id"))
	if err != nil {
		writeError(w, http.StatusNotFound, "account not found")
		return
	}
	if acc.Provider != "codex" {
		writeError(w, http.StatusBadRequest, "only supported for codex accounts")
		return
	}
	if s.vault == nil {
		writeError(w, http.StatusInternalServerError, "vault not configured")
		return
	}

	var body struct {
		// RedeemRequestID is an idempotency key generated by the caller. Older
		// dashboard builds sent a credit row's identifier here, so keep accepting
		// it while generating a fresh UUID when it is omitted.
		RedeemRequestID string `json:"redeem_request_id"`
		CreditID        string `json:"credit_id"`
	}
	if !decodeJSON(w, r, &body) {
		return
	}
	if body.RedeemRequestID == "" {
		body.RedeemRequestID = uuid.NewString()
	}

	creds, err := s.vault.Open(acc)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "could not decrypt credentials")
		return
	}
	if creds.AccessToken == "" {
		writeError(w, http.StatusBadRequest, "no access token available; re-authorize the connection")
		return
	}

	ctx, cancel := context.WithTimeout(r.Context(), 15*time.Second)
	defer cancel()

	result, cerr := consumeCodexResetCredit(ctx, creds.AccessToken, creds.Extra, body.RedeemRequestID, body.CreditID)
	if cerr != nil {
		writeError(w, http.StatusBadGateway, sanitizeProviderError(s.log, cerr, "Codex reset credit request failed"))
		return
	}
	writeJSON(w, http.StatusOK, result)
}

// ---- Codex reset credits helpers --------------------------------------------

const (
	codexResetCreditsURL        = "https://chatgpt.com/backend-api/wham/rate-limit-reset-credits"
	codexResetCreditsConsumeURL = "https://chatgpt.com/backend-api/wham/rate-limit-reset-credits/consume"
	codexUsageURL               = "https://chatgpt.com/backend-api/wham/usage"
)

// codexAccountID extracts the ChatGPT account ID from provider metadata.
func codexAccountID(extra map[string]string) string {
	if extra == nil {
		return ""
	}
	for _, key := range []string{"workspaceId", "accountId", "chatgptAccountId"} {
		if v := extra[key]; v != "" {
			return v
		}
	}
	return ""
}

// codexCreditInfo represents a single reset credit with status and expiry.
type codexCreditInfo struct {
	ID              string `json:"id,omitempty"`
	RedeemRequestID string `json:"redeem_request_id,omitempty"`
	Status          string `json:"status"`
	GrantedAt       string `json:"granted_at,omitempty"`
	ExpiresAt       string `json:"expires_at,omitempty"`
	Title           string `json:"title,omitempty"`
	Description     string `json:"description,omitempty"`
}

// codexUsageDetails represents Codex usage information including rate limits and reset credits.
type codexUsageDetails struct {
	UsageData    *codexUsageData        `json:"usage_data,omitempty"`
	ResetCredits *codexResetCreditsData `json:"reset_credits,omitempty"`
	Error        string                 `json:"error,omitempty"`
}

type codexUsageData struct {
	PlanType               string `json:"plan_type"`
	Allowed                bool   `json:"allowed"`
	LimitReached           bool   `json:"limit_reached"`
	PrimaryUsedPercent     int    `json:"primary_used_percent"`
	PrimaryResetAt         int64  `json:"primary_reset_at"`
	PrimaryWindowSeconds   int64  `json:"primary_window_seconds"`
	SecondaryUsedPercent   int    `json:"secondary_used_percent"`
	SecondaryResetAt       int64  `json:"secondary_reset_at"`
	SecondaryWindowSeconds int64  `json:"secondary_window_seconds"`
	CreditsBalance         string `json:"credits_balance"`
	HasCredits             bool   `json:"has_credits"`
	Unlimited              bool   `json:"unlimited"`
	ResetCreditsAvailable  int    `json:"reset_credits_available"`
}

type codexResetCreditsData struct {
	AvailableCount int               `json:"available_count"`
	Credits        []codexCreditInfo `json:"credits"`
}

// adminCodexUsageDetails fetches both usage data and reset credits for a Codex account.
func (s *Server) adminCodexUsageDetails(w http.ResponseWriter, r *http.Request) {
	acc, err := s.accounts.Get(r.Context(), chi.URLParam(r, "id"))
	if err != nil {
		writeError(w, http.StatusNotFound, "account not found")
		return
	}
	if acc.Provider != "codex" {
		writeError(w, http.StatusBadRequest, "only supported for codex accounts")
		return
	}
	if s.vault == nil {
		writeError(w, http.StatusInternalServerError, "vault not configured")
		return
	}

	creds, err := s.vault.Open(acc)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "could not decrypt credentials")
		return
	}
	if creds.AccessToken == "" {
		writeError(w, http.StatusBadRequest, "no access token available; re-authorize the connection")
		return
	}

	ctx, cancel := context.WithTimeout(r.Context(), 20*time.Second)
	defer cancel()

	// Usage windows and reset credits come from independent upstream endpoints.
	// Fetch them together so expanding an account costs one round-trip instead
	// of waiting for two sequential network calls.
	var (
		usageData    *codexUsageData
		usageErr     error
		resetCredits codexResetCreditsData
		resetErr     error
		wg           sync.WaitGroup
	)
	wg.Add(2)
	go func() {
		defer wg.Done()
		usageData, usageErr = fetchCodexUsage(ctx, creds.AccessToken, creds.Extra)
	}()
	go func() {
		defer wg.Done()
		resetCredits, resetErr = fetchCodexResetCredits(ctx, creds.AccessToken, creds.Extra)
	}()
	wg.Wait()

	result := codexUsageDetails{}

	if usageErr == nil && usageData != nil {
		result.UsageData = usageData
	} else {
		result.Error = "Failed to fetch usage data"
		if usageErr != nil {
			result.Error = sanitizeProviderError(s.log, usageErr, "Codex usage request failed")
		}
	}

	if resetErr == nil {
		result.ResetCredits = &codexResetCreditsData{
			AvailableCount: resetCredits.AvailableCount,
			Credits:        resetCredits.Credits,
		}
	} else {
		if result.Error != "" {
			result.Error += "; Failed to fetch reset credits"
		} else {
			result.Error = "Failed to fetch reset credits"
		}
	}

	writeJSON(w, http.StatusOK, result)
}

// fetchCodexUsage retrieves Codex usage data from the ChatGPT backend API.
// The wham/usage endpoint returns rate limits as percentage-based windows
// (primary = 5h rolling, secondary = weekly), plus credits and reset credits.
func fetchCodexUsage(ctx context.Context, accessToken string, extra map[string]string) (*codexUsageData, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, codexUsageURL, nil)
	if err != nil {
		return nil, fmt.Errorf("build request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+accessToken)
	req.Header.Set("Accept", "application/json")
	req.Header.Set("OpenAI-Beta", "codex-1")
	req.Header.Set("originator", "codex_cli_rs")
	req.Header.Set("User-Agent", "codex-cli-rs/0.1.0")
	if accountID := codexAccountID(extra); accountID != "" {
		req.Header.Set("ChatGPT-Account-ID", accountID)
	}

	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	bodyBytes, readErr := io.ReadAll(resp.Body)
	if readErr != nil {
		return nil, fmt.Errorf("read response: %w", readErr)
	}

	if resp.StatusCode >= 400 {
		var errData struct {
			Message string `json:"message"`
			Error   string `json:"error"`
			Detail  string `json:"detail"`
		}
		_ = json.Unmarshal(bodyBytes, &errData)
		msg := errData.Message
		if msg == "" {
			msg = errData.Error
		}
		if msg == "" {
			msg = errData.Detail
		}
		if msg == "" {
			msg = fmt.Sprintf("Codex usage API unavailable (%d): %s", resp.StatusCode, string(bodyBytes))
		}
		return nil, fmt.Errorf("%s", msg)
	}

	var raw struct {
		PlanType  string `json:"plan_type"`
		RateLimit struct {
			Allowed       bool `json:"allowed"`
			LimitReached  bool `json:"limit_reached"`
			PrimaryWindow struct {
				UsedPercent        int   `json:"used_percent"`
				LimitWindowSeconds int64 `json:"limit_window_seconds"`
				ResetAfterSeconds  int64 `json:"reset_after_seconds"`
				ResetAt            int64 `json:"reset_at"`
			} `json:"primary_window"`
			SecondaryWindow struct {
				UsedPercent        int   `json:"used_percent"`
				LimitWindowSeconds int64 `json:"limit_window_seconds"`
				ResetAfterSeconds  int64 `json:"reset_after_seconds"`
				ResetAt            int64 `json:"reset_at"`
			} `json:"secondary_window"`
		} `json:"rate_limit"`
		Credits struct {
			HasCredits bool   `json:"has_credits"`
			Unlimited  bool   `json:"unlimited"`
			Balance    string `json:"balance"`
		} `json:"credits"`
		RateLimitResetCredits struct {
			AvailableCount int `json:"available_count"`
		} `json:"rate_limit_reset_credits"`
	}
	if err := json.Unmarshal(bodyBytes, &raw); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}

	return &codexUsageData{
		PlanType:               raw.PlanType,
		Allowed:                raw.RateLimit.Allowed,
		LimitReached:           raw.RateLimit.LimitReached,
		PrimaryUsedPercent:     raw.RateLimit.PrimaryWindow.UsedPercent,
		PrimaryResetAt:         raw.RateLimit.PrimaryWindow.ResetAt,
		PrimaryWindowSeconds:   raw.RateLimit.PrimaryWindow.LimitWindowSeconds,
		SecondaryUsedPercent:   raw.RateLimit.SecondaryWindow.UsedPercent,
		SecondaryResetAt:       raw.RateLimit.SecondaryWindow.ResetAt,
		SecondaryWindowSeconds: raw.RateLimit.SecondaryWindow.LimitWindowSeconds,
		CreditsBalance:         raw.Credits.Balance,
		HasCredits:             raw.Credits.HasCredits,
		Unlimited:              raw.Credits.Unlimited,
		ResetCreditsAvailable:  raw.RateLimitResetCredits.AvailableCount,
	}, nil
}

// fetchCodexResetCredits retrieves available Codex rate-limit reset credits.
func fetchCodexResetCredits(ctx context.Context, accessToken string, extra map[string]string) (codexResetCreditsData, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, codexResetCreditsURL, nil)
	if err != nil {
		return codexResetCreditsData{}, fmt.Errorf("build request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+accessToken)
	req.Header.Set("Accept", "application/json")
	req.Header.Set("OpenAI-Beta", "codex-1")
	req.Header.Set("originator", "codex_cli_rs")
	if accountID := codexAccountID(extra); accountID != "" {
		req.Header.Set("ChatGPT-Account-ID", accountID)
	}

	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return codexResetCreditsData{}, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	var data struct {
		AvailableCount  *int `json:"available_count"`
		AvailableCount2 *int `json:"availableCount"`
		Credits         []struct {
			ID               string `json:"id"`
			CreditID         string `json:"credit_id"`
			RedeemRequestID  string `json:"redeem_request_id"`
			RedeemRequestID2 string `json:"redeemRequestId"`
			Status           string `json:"status"`
			GrantedAt        any    `json:"granted_at"`
			GrantedAt2       any    `json:"grantedAt"`
			ExpiresAt        any    `json:"expires_at"`
			ExpiresAt2       any    `json:"expiresAt"`
			Title            string `json:"title"`
			Description      string `json:"description"`
		} `json:"credits"`
		Message string `json:"message"`
		Error   string `json:"error"`
		Detail  string `json:"detail"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&data); err != nil {
		if resp.StatusCode >= 400 {
			msg := data.Message
			if msg == "" {
				msg = data.Error
			}
			if msg == "" {
				msg = data.Detail
			}
			if msg == "" {
				msg = fmt.Sprintf("Codex reset credits API unavailable (%d)", resp.StatusCode)
			}
			return codexResetCreditsData{}, fmt.Errorf("%s", msg)
		}
		return codexResetCreditsData{}, fmt.Errorf("decode response: %w", err)
	}
	if resp.StatusCode >= 400 {
		msg := data.Message
		if msg == "" {
			msg = data.Error
		}
		if msg == "" {
			msg = data.Detail
		}
		if msg == "" {
			msg = fmt.Sprintf("Codex reset credits API unavailable (%d)", resp.StatusCode)
		}
		return codexResetCreditsData{}, fmt.Errorf("%s", msg)
	}

	available := 0
	if data.AvailableCount != nil {
		available = *data.AvailableCount
	} else if data.AvailableCount2 != nil {
		available = *data.AvailableCount2
	}

	credits := make([]codexCreditInfo, 0, len(data.Credits))
	for _, c := range data.Credits {
		info := codexCreditInfo{
			ID:              c.ID,
			RedeemRequestID: c.RedeemRequestID,
			Status:          defaultStr(c.Status, "unknown"),
			Title:           c.Title,
			Description:     c.Description,
		}
		if info.ID == "" {
			info.ID = c.CreditID
		}
		if info.RedeemRequestID == "" && c.RedeemRequestID2 != "" {
			info.RedeemRequestID = c.RedeemRequestID2
		}
		info.GrantedAt = codexTimeString(c.GrantedAt)
		if info.GrantedAt == "" {
			info.GrantedAt = codexTimeString(c.GrantedAt2)
		}
		info.ExpiresAt = codexTimeString(c.ExpiresAt)
		if info.ExpiresAt == "" {
			info.ExpiresAt = codexTimeString(c.ExpiresAt2)
		}
		credits = append(credits, info)
	}

	return codexResetCreditsData{
		AvailableCount: available,
		Credits:        credits,
	}, nil
}

// codexTimeString normalizes the reset-credit API's mixed timestamp formats.
// The upstream has returned both RFC3339 strings and Unix seconds/milliseconds.
func codexTimeString(value any) string {
	switch v := value.(type) {
	case string:
		return v
	case float64:
		seconds := int64(v)
		if seconds > 10_000_000_000 {
			seconds /= 1000
		}
		if seconds > 0 {
			return time.Unix(seconds, 0).UTC().Format(time.RFC3339)
		}
	case json.Number:
		if number, err := v.Int64(); err == nil {
			return codexTimeString(float64(number))
		}
	}
	return ""
}

// consumeCodexResetCredit consumes one Codex rate-limit reset credit.
func consumeCodexResetCredit(ctx context.Context, accessToken string, extra map[string]string, redeemRequestID, creditID string) (map[string]any, error) {
	req, err := newCodexResetRequest(ctx, accessToken, extra, redeemRequestID, creditID)
	if err != nil {
		return nil, err
	}

	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	return parseCodexConsumeResponse(resp.StatusCode, body), nil
}

func newCodexResetRequest(ctx context.Context, accessToken string, extra map[string]string, redeemRequestID, creditID string) (*http.Request, error) {
	payloadData := map[string]string{
		"redeem_request_id": redeemRequestID,
	}
	if creditID != "" {
		payloadData["credit_id"] = creditID
	}
	payload, _ := json.Marshal(payloadData)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, codexResetCreditsConsumeURL,
		bytes.NewReader(payload))
	if err != nil {
		return nil, fmt.Errorf("build request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+accessToken)
	req.Header.Set("Accept", "application/json")
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("OpenAI-Beta", "codex-1")
	req.Header.Set("originator", "codex_cli_rs")
	req.Header.Set("User-Agent", "codex-cli-rs/0.1.0")
	if accountID := codexAccountID(extra); accountID != "" {
		req.Header.Set("ChatGPT-Account-ID", accountID)
	}
	return req, nil
}
